-- +goose Up
-- +goose StatementBegin

-- Goose 会在执行首个 migration 前创建同构表；显式声明让 sqlc 也能解析并校验其注释。
CREATE TABLE IF NOT EXISTS goose_db_version (
    id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    version_id bigint NOT NULL,
    is_applied boolean NOT NULL,
    tstamp timestamp NOT NULL DEFAULT now()
);

CREATE TABLE tenants (
    id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    name text NOT NULL,
    status text NOT NULL DEFAULT 'active',
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT tenants_name_not_blank CHECK (btrim(name) <> ''),
    CONSTRAINT tenants_status_valid CHECK (status IN ('active', 'suspended'))
);

COMMENT ON TABLE tenants IS '控制面租户，定义所有业务数据和授权的一级隔离边界';
COMMENT ON COLUMN tenants.id IS '租户稳定标识，跨控制面资源关联使用的 UUID';
COMMENT ON COLUMN tenants.name IS '租户显示名称，不作为登录名或全局唯一业务键';
COMMENT ON COLUMN tenants.status IS '租户状态：active 可处理业务，suspended 禁止新增副作用';
COMMENT ON COLUMN tenants.created_at IS '租户记录创建时间，使用数据库时区时间';
COMMENT ON COLUMN tenants.updated_at IS '租户业务状态最后更新时间，使用数据库时区时间';

CREATE TABLE domains (
    id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    tenant_id uuid NOT NULL REFERENCES tenants (id),
    name text NOT NULL,
    status text NOT NULL DEFAULT 'active',
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT domains_name_normalized CHECK (
        name = lower(name)
        AND name = btrim(name)
        AND char_length(name) BETWEEN 1 AND 253
        AND right(name, 1) <> '.'
    ),
    CONSTRAINT domains_status_valid CHECK (status IN ('active', 'suspended')),
    CONSTRAINT domains_name_unique UNIQUE (name),
    CONSTRAINT domains_id_tenant_unique UNIQUE (id, tenant_id)
);

COMMENT ON TABLE domains IS '租户拥有的邮件域名，仅 active 域名可接收新的邮箱开通意图';
COMMENT ON COLUMN domains.id IS '邮件域名稳定标识，邮箱开通命令通过该标识引用域名';
COMMENT ON COLUMN domains.tenant_id IS '域名所属租户标识，用于强制租户隔离';
COMMENT ON COLUMN domains.name IS '小写规范化后的邮件域名，全局唯一，不包含尾随点';
COMMENT ON COLUMN domains.status IS '域名状态：active 可开通邮箱，suspended 禁止新增邮箱';
COMMENT ON COLUMN domains.created_at IS '域名记录创建时间，使用数据库时区时间';
COMMENT ON COLUMN domains.updated_at IS '域名状态或属性最后更新时间，使用数据库时区时间';

CREATE TABLE mailboxes (
    id uuid PRIMARY KEY,
    tenant_id uuid NOT NULL REFERENCES tenants (id),
    domain_id uuid NOT NULL,
    local_part text NOT NULL,
    display_name text,
    desired_status text NOT NULL DEFAULT 'active',
    observed_status text NOT NULL DEFAULT 'unknown',
    revision bigint NOT NULL DEFAULT 1,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT mailboxes_domain_tenant_fk
        FOREIGN KEY (domain_id, tenant_id) REFERENCES domains (id, tenant_id),
    CONSTRAINT mailboxes_local_part_normalized CHECK (
        local_part = lower(local_part)
        AND octet_length(local_part) BETWEEN 1 AND 64
        AND local_part ~ '^[a-z0-9.!#$%&''*+/=?^_`{|}~-]+$'
        AND left(local_part, 1) <> '.'
        AND right(local_part, 1) <> '.'
        AND position('..' IN local_part) = 0
    ),
    CONSTRAINT mailboxes_display_name_valid CHECK (
        display_name IS NULL OR (display_name = btrim(display_name) AND char_length(display_name) BETWEEN 1 AND 128)
    ),
    CONSTRAINT mailboxes_desired_status_valid CHECK (desired_status IN ('active', 'suspended', 'deleted')),
    CONSTRAINT mailboxes_observed_status_valid CHECK (observed_status IN ('unknown', 'active', 'suspended', 'deleted', 'failed')),
    CONSTRAINT mailboxes_revision_positive CHECK (revision > 0),
    CONSTRAINT mailboxes_domain_local_part_unique UNIQUE (domain_id, local_part)
);

COMMENT ON TABLE mailboxes IS '控制面邮箱期望状态，不保存原始邮件或 mail-core 内部数据';
COMMENT ON COLUMN mailboxes.id IS '邮箱稳定标识，在公开契约和 operation 中引用';
COMMENT ON COLUMN mailboxes.tenant_id IS '邮箱所属租户标识，所有读取和变更必须同时限定该字段';
COMMENT ON COLUMN mailboxes.domain_id IS '邮箱所属邮件域名标识，必须与 tenant_id 属于同一租户';
COMMENT ON COLUMN mailboxes.local_part IS '小写规范化后的邮箱本地部分，v0.1 仅允许 ASCII';
COMMENT ON COLUMN mailboxes.display_name IS '可选邮箱显示名称，去除首尾空白后最多 128 个字符';
COMMENT ON COLUMN mailboxes.desired_status IS '控制面期望状态，由业务请求推进，不代表 mail-core 已完成';
COMMENT ON COLUMN mailboxes.observed_status IS 'mail-core 最近一次观测状态，新请求在执行前为 unknown';
COMMENT ON COLUMN mailboxes.revision IS '邮箱期望状态版本，用于 worker fencing 和乱序回执判断';
COMMENT ON COLUMN mailboxes.created_at IS '邮箱意图首次创建时间，使用数据库时区时间';
COMMENT ON COLUMN mailboxes.updated_at IS '邮箱期望或观测状态最后更新时间，使用数据库时区时间';

CREATE TABLE operations (
    id uuid PRIMARY KEY,
    tenant_id uuid NOT NULL REFERENCES tenants (id),
    kind text NOT NULL,
    resource_type text NOT NULL,
    resource_id uuid NOT NULL,
    status text NOT NULL DEFAULT 'pending',
    idempotency_key text NOT NULL,
    request_hash bytea NOT NULL,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT operations_kind_valid CHECK (kind IN ('mailbox.provision')),
    CONSTRAINT operations_resource_type_valid CHECK (resource_type IN ('mailbox')),
    CONSTRAINT operations_status_valid CHECK (status IN ('pending', 'running', 'succeeded', 'failed', 'unknown')),
    CONSTRAINT operations_idempotency_key_valid CHECK (
        char_length(idempotency_key) BETWEEN 16 AND 128
        AND idempotency_key ~ '^[A-Za-z0-9._:-]+$'
    ),
    CONSTRAINT operations_request_hash_sha256 CHECK (octet_length(request_hash) = 32),
    CONSTRAINT operations_tenant_idempotency_unique UNIQUE (tenant_id, idempotency_key),
    CONSTRAINT operations_id_tenant_unique UNIQUE (id, tenant_id)
);

COMMENT ON TABLE operations IS '跨系统副作用的控制面状态事实源，支持幂等、领取、重试和审计';
COMMENT ON COLUMN operations.id IS 'operation 稳定标识，供状态查询和链路关联';
COMMENT ON COLUMN operations.tenant_id IS 'operation 所属租户标识，幂等与查询均在租户内生效';
COMMENT ON COLUMN operations.kind IS '副作用类型，v0.1 仅支持 mailbox.provision';
COMMENT ON COLUMN operations.resource_type IS '目标资源类型，v0.1 仅支持 mailbox';
COMMENT ON COLUMN operations.resource_id IS '目标业务资源稳定标识，本表不建立多态外键';
COMMENT ON COLUMN operations.status IS 'operation 状态：pending、running、succeeded、failed 或 unknown';
COMMENT ON COLUMN operations.idempotency_key IS '调用方提供的租户内幂等键，不得包含凭据或业务正文';
COMMENT ON COLUMN operations.request_hash IS '规范化业务请求的 SHA-256 指纹，用于识别幂等键复用冲突';
COMMENT ON COLUMN operations.created_at IS 'operation 首次创建时间，重放请求不得修改';
COMMENT ON COLUMN operations.updated_at IS 'operation 状态最后更新时间，重放查询不得修改';

CREATE INDEX operations_tenant_status_created_idx
    ON operations (tenant_id, status, created_at, id);

CREATE TABLE outbox_events (
    id uuid PRIMARY KEY,
    tenant_id uuid NOT NULL REFERENCES tenants (id),
    operation_id uuid NOT NULL,
    event_type text NOT NULL,
    payload jsonb NOT NULL,
    status text NOT NULL DEFAULT 'pending',
    attempts integer NOT NULL DEFAULT 0,
    next_attempt_at timestamptz NOT NULL DEFAULT now(),
    delivered_at timestamptz,
    created_at timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT outbox_events_operation_tenant_fk
        FOREIGN KEY (operation_id, tenant_id) REFERENCES operations (id, tenant_id),
    CONSTRAINT outbox_events_event_type_valid CHECK (event_type IN ('mailbox.provision.requested')),
    CONSTRAINT outbox_events_payload_object CHECK (jsonb_typeof(payload) = 'object'),
    CONSTRAINT outbox_events_status_valid CHECK (status IN ('pending', 'processing', 'delivered', 'dead')),
    CONSTRAINT outbox_events_attempts_nonnegative CHECK (attempts >= 0),
    CONSTRAINT outbox_events_operation_unique UNIQUE (operation_id)
);

COMMENT ON TABLE outbox_events IS '与业务意图同事务写入的待分发事件，不作为 operation 状态事实源';
COMMENT ON COLUMN outbox_events.id IS 'outbox 事件稳定标识，用于领取和投递去重';
COMMENT ON COLUMN outbox_events.tenant_id IS '事件所属租户标识，消费和审计必须保持租户边界';
COMMENT ON COLUMN outbox_events.operation_id IS '触发该事件的 operation 标识，v0.1 每个 operation 仅一条首发事件';
COMMENT ON COLUMN outbox_events.event_type IS '事件类型，v0.1 固定为 mailbox.provision.requested';
COMMENT ON COLUMN outbox_events.payload IS '只含稳定资源标识与 revision 的 JSON 对象，不含邮件地址或凭据';
COMMENT ON COLUMN outbox_events.status IS '分发状态：pending、processing、delivered 或 dead';
COMMENT ON COLUMN outbox_events.attempts IS '已经发起的分发尝试次数，初始为 0';
COMMENT ON COLUMN outbox_events.next_attempt_at IS '下一次允许领取事件的时间，用于有界退避';
COMMENT ON COLUMN outbox_events.delivered_at IS '事件成功分发时间，未成功时为空';
COMMENT ON COLUMN outbox_events.created_at IS '事件与业务意图同事务创建的时间';

CREATE INDEX outbox_events_status_next_attempt_idx
    ON outbox_events (status, next_attempt_at, id);

COMMENT ON TABLE goose_db_version IS 'Goose 数据库迁移版本记录，由 migrator 独占维护';
COMMENT ON COLUMN goose_db_version.id IS '迁移记录自增主键，由 Goose 内部使用';
COMMENT ON COLUMN goose_db_version.version_id IS '迁移版本号，对应 migration 文件的数字前缀';
COMMENT ON COLUMN goose_db_version.is_applied IS '迁移是否处于已应用状态，由 Goose 维护';
COMMENT ON COLUMN goose_db_version.tstamp IS '迁移版本记录写入时间，由 Goose 维护';

-- +goose StatementEnd

-- +goose Down
-- +goose StatementBegin

DROP TABLE outbox_events;
DROP TABLE operations;
DROP TABLE mailboxes;
DROP TABLE domains;
DROP TABLE tenants;

-- +goose StatementEnd
